language: julia

os:
    - linux

julia:
    - 0.7
    - 1.0
    - nightly

script:
    - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaFEM/FEMQuad.jl"));
                           Pkg.add(PackageSpec(path=pwd()));
                           Pkg.build("FEMBase");
                           Pkg.test("FEMBase"; coverage=true)'

after_success:
    - julia -e 'cd(Pkg.dir("FEMBase")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
